# Starter pipeline
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'dockerhub'
    dockerComposeFile: 'tedcwe/azcompose/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '-d'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- task: SSH@0
  inputs:
    sshEndpoint: '10.0.0.4'
    runOptions: 'inline'
    inline: 'touch file{1..1000}'
    readyTimeout: '20000'
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
